/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;

/**
 *
 * @author dinhp
 */
public class IntroGUI extends javax.swing.JPanel {

    /**
     * Creates new form IntroGUI
     */
    public IntroGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelCanhan = new my_component.RoundedPanel();
        Thongtincanhan = new my_component.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        Avatar = new javax.swing.JLabel();
        manv = new javax.swing.JLabel();
        hoten = new javax.swing.JLabel();
        ngaysinh = new javax.swing.JLabel();
        vaitro = new javax.swing.JLabel();
        gioitinh = new javax.swing.JLabel();
        sodienthoai = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        ngayvaolam = new javax.swing.JLabel();
        txhoten = new javax.swing.JLabel();
        txngaysinh = new javax.swing.JLabel();
        txvaitro = new javax.swing.JLabel();
        txngayvaolam = new javax.swing.JLabel();
        txgioitinh = new javax.swing.JLabel();
        txsodienthoai = new javax.swing.JLabel();
        txemail = new javax.swing.JLabel();
        PanelDoimatkhau = new my_component.RoundedPanel();
        Doimatkhau = new my_component.RoundedPanel();
        txtDoimatkhau = new javax.swing.JLabel();
        matkhaucu = new javax.swing.JLabel();
        textmatkhaucu = new testlib.RoundedTextField();
        matkhaumoi = new javax.swing.JLabel();
        textmatkhaumoi = new testlib.RoundedTextField();
        matkhaumoi2 = new javax.swing.JLabel();
        textmatkhaumoi2 = new testlib.RoundedTextField();
        btnDoimatkhau = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Thongtincanhan.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Thông tin cá nhân");

        javax.swing.GroupLayout ThongtincanhanLayout = new javax.swing.GroupLayout(Thongtincanhan);
        Thongtincanhan.setLayout(ThongtincanhanLayout);
        ThongtincanhanLayout.setHorizontalGroup(
            ThongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongtincanhanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThongtincanhanLayout.setVerticalGroup(
            ThongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongtincanhanLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Screenshot 2025-04-12 023629.png"))); // NOI18N

        manv.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        manv.setText("Truy xuất mã nv");

        hoten.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        hoten.setText("Họ tên");

        ngaysinh.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ngaysinh.setText("Ngày sinh");

        vaitro.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        vaitro.setText("Vai trò");

        gioitinh.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        gioitinh.setText("Giới tính");

        sodienthoai.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        sodienthoai.setText("Số điện thoại");

        email.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        email.setText("Email");

        ngayvaolam.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        ngayvaolam.setText("Ngày vào làm");

        txhoten.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txhoten.setText("Truy xuất tên nhân viên");
        txhoten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txngaysinh.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txngaysinh.setText("Truy xuất ngày sinh");
        txngaysinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txvaitro.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txvaitro.setText("Truy xuất vai trò");
        txvaitro.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txngayvaolam.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txngayvaolam.setText("Truy xuất ngày vào làm");
        txngayvaolam.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txgioitinh.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txgioitinh.setText("Truy xuất giới tính");
        txgioitinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txsodienthoai.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txsodienthoai.setText("Truy xuất số điện thoại");
        txsodienthoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txemail.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        txemail.setText("Truy xuất Email");
        txemail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelCanhanLayout = new javax.swing.GroupLayout(PanelCanhan);
        PanelCanhan.setLayout(PanelCanhanLayout);
        PanelCanhanLayout.setHorizontalGroup(
            PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Thongtincanhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelCanhanLayout.createSequentialGroup()
                .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCanhanLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Avatar))
                    .addGroup(PanelCanhanLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCanhanLayout.createSequentialGroup()
                        .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hoten)
                            .addComponent(txhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelCanhanLayout.createSequentialGroup()
                        .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaysinh)
                            .addComponent(vaitro)
                            .addComponent(ngayvaolam)
                            .addComponent(txngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email)
                            .addComponent(sodienthoai)
                            .addComponent(txgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gioitinh)
                            .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150))))
        );
        PanelCanhanLayout.setVerticalGroup(
            PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCanhanLayout.createSequentialGroup()
                .addComponent(Thongtincanhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCanhanLayout.createSequentialGroup()
                        .addComponent(Avatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manv))
                    .addGroup(PanelCanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(PanelCanhanLayout.createSequentialGroup()
                            .addComponent(gioitinh)
                            .addGap(12, 12, 12)
                            .addComponent(txgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(sodienthoai)
                            .addGap(10, 10, 10)
                            .addComponent(txsodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(email)
                            .addGap(10, 10, 10)
                            .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelCanhanLayout.createSequentialGroup()
                            .addComponent(hoten)
                            .addGap(12, 12, 12)
                            .addComponent(txhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(ngaysinh)
                            .addGap(10, 10, 10)
                            .addComponent(txngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(vaitro)
                            .addGap(10, 10, 10)
                            .addComponent(txvaitro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(ngayvaolam)
                            .addGap(10, 10, 10)
                            .addComponent(txngayvaolam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Doimatkhau.setBackground(new java.awt.Color(153, 153, 153));

        txtDoimatkhau.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtDoimatkhau.setText("Đổi mật khẩu");

        javax.swing.GroupLayout DoimatkhauLayout = new javax.swing.GroupLayout(Doimatkhau);
        Doimatkhau.setLayout(DoimatkhauLayout);
        DoimatkhauLayout.setHorizontalGroup(
            DoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoimatkhauLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtDoimatkhau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoimatkhauLayout.setVerticalGroup(
            DoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoimatkhauLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(txtDoimatkhau)
                .addContainerGap())
        );

        matkhaucu.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        matkhaucu.setText("Mật khẩu cũ:");

        textmatkhaucu.setText("Nhập mật khẩu cũ");
        textmatkhaucu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nhapchu(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lammo(evt);
            }
        });

        matkhaumoi.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        matkhaumoi.setText("Mật khẩu mới:");

        textmatkhaumoi.setText("Nhập mật khẩu mới");
        textmatkhaumoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nhapchuMkmoi(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lammoMkmoi(evt);
            }
        });

        matkhaumoi2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        matkhaumoi2.setText("Nhập lại mật khẩu mới:");

        textmatkhaumoi2.setText("Nhập lại mật khẩu mới");
        textmatkhaumoi2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nhapchuMkmoi2(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lammoMkmoi2(evt);
            }
        });

        btnDoimatkhau.setBackground(new java.awt.Color(153, 153, 153));
        btnDoimatkhau.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnDoimatkhau.setText("Đổi mật khẩu");

        javax.swing.GroupLayout PanelDoimatkhauLayout = new javax.swing.GroupLayout(PanelDoimatkhau);
        PanelDoimatkhau.setLayout(PanelDoimatkhauLayout);
        PanelDoimatkhauLayout.setHorizontalGroup(
            PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Doimatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDoimatkhauLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelDoimatkhauLayout.createSequentialGroup()
                        .addComponent(matkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelDoimatkhauLayout.createSequentialGroup()
                            .addComponent(matkhaumoi2)
                            .addGap(37, 37, 37)
                            .addComponent(textmatkhaumoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelDoimatkhauLayout.createSequentialGroup()
                            .addComponent(matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(textmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86)
                .addComponent(btnDoimatkhau)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        PanelDoimatkhauLayout.setVerticalGroup(
            PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDoimatkhauLayout.createSequentialGroup()
                .addComponent(Doimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textmatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textmatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelDoimatkhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matkhaumoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textmatkhaumoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoimatkhau))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCanhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PanelCanhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(PanelDoimatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nhapchu(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nhapchu
        if(textmatkhaucu.getText().equals("Nhập mật khẩu cũ")){
            textmatkhaucu.setText("");
            textmatkhaucu.setForeground(Color.BLACK);
        }
        else
        textmatkhaucu.selectAll();
    }//GEN-LAST:event_nhapchu

    private void lammo(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lammo
        if(textmatkhaucu.getText().trim().isEmpty()){
            textmatkhaucu.setText("Nhập mật khẩu cũ");
            textmatkhaucu.setForeground(Color.black);
        }
    }//GEN-LAST:event_lammo

    private void nhapchuMkmoi(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nhapchuMkmoi
        if(textmatkhaumoi.getText().equals("Nhập mật khẩu mới")){
            textmatkhaumoi.setText("");
            textmatkhaumoi.setForeground(Color.BLACK);
        }
        else
        textmatkhaumoi.selectAll();
    }//GEN-LAST:event_nhapchuMkmoi

    private void lammoMkmoi(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lammoMkmoi
        if(textmatkhaumoi.getText().trim().isEmpty()){
            textmatkhaumoi.setText("Nhập mật khẩu mới");
            textmatkhaumoi.setForeground(Color.black);
        }
    }//GEN-LAST:event_lammoMkmoi

    private void nhapchuMkmoi2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nhapchuMkmoi2
        if(textmatkhaumoi2.getText().equals("Nhập lại mật khẩu mới")){
            textmatkhaumoi2.setText("");
            textmatkhaumoi2.setForeground(Color.BLACK);
        }
        else
        textmatkhaumoi2.selectAll();
    }//GEN-LAST:event_nhapchuMkmoi2

    private void lammoMkmoi2(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lammoMkmoi2
        if(textmatkhaumoi2.getText().trim().isEmpty()){
            textmatkhaumoi2.setText("Nhập lại mật khẩu mới");
            textmatkhaumoi2.setForeground(Color.black);
        }
    }//GEN-LAST:event_lammoMkmoi2


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Avatar;
    private my_component.RoundedPanel Doimatkhau;
    private my_component.RoundedPanel PanelCanhan;
    private my_component.RoundedPanel PanelDoimatkhau;
    private my_component.RoundedPanel Thongtincanhan;
    private javax.swing.JButton btnDoimatkhau;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gioitinh;
    private javax.swing.JLabel hoten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manv;
    private javax.swing.JLabel matkhaucu;
    private javax.swing.JLabel matkhaumoi;
    private javax.swing.JLabel matkhaumoi2;
    private javax.swing.JLabel ngaysinh;
    private javax.swing.JLabel ngayvaolam;
    private javax.swing.JLabel sodienthoai;
    private testlib.RoundedTextField textmatkhaucu;
    private testlib.RoundedTextField textmatkhaumoi;
    private testlib.RoundedTextField textmatkhaumoi2;
    private javax.swing.JLabel txemail;
    private javax.swing.JLabel txgioitinh;
    private javax.swing.JLabel txhoten;
    private javax.swing.JLabel txngaysinh;
    private javax.swing.JLabel txngayvaolam;
    private javax.swing.JLabel txsodienthoai;
    private javax.swing.JLabel txtDoimatkhau;
    private javax.swing.JLabel txvaitro;
    private javax.swing.JLabel vaitro;
    // End of variables declaration//GEN-END:variables
}
