/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import DAO.ChucNangDAO;
import DAO.PhanQuyenDAO;
import DTO.PhanQuyenDTO;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import log_reg.UI;
/**
 *
 * @author dinhp
 */
public class PhanquyenGUI extends javax.swing.JPanel {
 public CardLayout card = new CardLayout();
    private PhanQuyenDAO phanQuyenDAO;
    private ChucNangDAO chucNangDAO;
    private DefaultTableModel tableModel;
    public PhanquyenGUI() {
        initComponents();
                Giaodien.setLayout(new CardLayout());
                Giaodien.add(ThemPhanquyen,"Them");
                Giaodien.add(XemPhanquyen,"Xem");
                UI.addPlaceHolderEffect(txtNhapten, "Nhập tên phân quyền");
                   // Khởi tạo DAO
        phanQuyenDAO = new PhanQuyenDAO();
        chucNangDAO = new ChucNangDAO();
        
        // Thiết lập model cho bảng phân quyền
        tableModel = (DefaultTableModel) tbPhanquyen.getModel();
        
        // Load dữ liệu phân quyền vào bảng
        loadTableData();
        
        // Thêm sự kiện cho nút "Thêm quyền"
        btnThemquyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemquyenActionPerformed(evt);
            }
        });
        
        // Thêm sự kiện cho các nút chức năng
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });
        
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        
        btnXoaphieu.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXoaphieuActionPerformed(evt);
    }
});

btnChitiet.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnChitietActionPerformed(evt);
    }
});

// Thêm sự kiện để xử lý click vào bảng phân quyền
tbPhanquyen.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tbPhanquyen.getSelectedRow();
        if (selectedRow >= 0) {
            // Có thể thêm code ở đây để cập nhật thông tin khi click vào bảng nếu cần
        }
    }
});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThanhChucnang = new javax.swing.JPanel();
        btnXem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaphieu = new javax.swing.JButton();
        btnChitiet = new javax.swing.JButton();
        Giaodien = new javax.swing.JPanel();
        XemPhanquyen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhanquyen = new javax.swing.JTable();
        ThemPhanquyen = new javax.swing.JPanel();
        PanPhanquyen = new javax.swing.JPanel();
        Nhapten = new javax.swing.JLabel();
        txtNhapten = new javax.swing.JTextField();
        Quanlychucnang = new javax.swing.JLabel();
        txQuanlysach = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txQuanlynhanvien = new javax.swing.JLabel();
        txQuanlyphieunhapsach = new javax.swing.JLabel();
        txQuanlydocgia = new javax.swing.JLabel();
        txQuanlyphanquyen = new javax.swing.JLabel();
        txQuanlyphieumuon = new javax.swing.JLabel();
        txQuanlytaikhoan = new javax.swing.JLabel();
        txQuanlythongke = new javax.swing.JLabel();
        txQuanlynguonnhap = new javax.swing.JLabel();
        Quanlyphim = new javax.swing.JCheckBox();
        Quanlylichchieu = new javax.swing.JCheckBox();
        Quanlyphongchieu = new javax.swing.JCheckBox();
        Quanlyanvat = new javax.swing.JCheckBox();
        Quanlyuudai = new javax.swing.JCheckBox();
        Quanlynhanvien = new javax.swing.JCheckBox();
        Quanlykhachhang = new javax.swing.JCheckBox();
        Quanlythongke = new javax.swing.JCheckBox();
        Quanlyhopdong = new javax.swing.JCheckBox();
        btnThemquyen = new javax.swing.JButton();
        txQuanlysach1 = new javax.swing.JLabel();
        Quanlynpp = new javax.swing.JCheckBox();
        txQuanlysach2 = new javax.swing.JLabel();
        Quanlytaikhoan = new javax.swing.JCheckBox();
        txQuanlysach3 = new javax.swing.JLabel();
        Quanlyphanquyen = new javax.swing.JCheckBox();

        jPanel1.setPreferredSize(new java.awt.Dimension(1092, 533));

        ThanhChucnang.setBackground(new java.awt.Color(255, 255, 255));
        ThanhChucnang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        btnXem.setBackground(new java.awt.Color(153, 153, 153));
        btnXem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        btnXem.setText("Xem");
        btnXem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXem.setContentAreaFilled(false);
        btnXem.setFocusPainted(false);
        btnXem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXem.setMaximumSize(new java.awt.Dimension(50, 72));
        btnXem.setMinimumSize(new java.awt.Dimension(50, 72));
        btnXem.setPreferredSize(new java.awt.Dimension(50, 72));
        btnXem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThem.setContentAreaFilled(false);
        btnThem.setFocusPainted(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaphieu.setBackground(new java.awt.Color(153, 153, 153));
        btnXoaphieu.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaphieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_i.png"))); // NOI18N
        btnXoaphieu.setText("Xóa phân quyền");
        btnXoaphieu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoaphieu.setContentAreaFilled(false);
        btnXoaphieu.setFocusPainted(false);
        btnXoaphieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaphieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnChitiet.setBackground(new java.awt.Color(153, 153, 153));
        btnChitiet.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnChitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/update.png"))); // NOI18N
        btnChitiet.setText("Chi tiết");
        btnChitiet.setToolTipText("");
        btnChitiet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChitiet.setContentAreaFilled(false);
        btnChitiet.setFocusPainted(false);
        btnChitiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChitiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout ThanhChucnangLayout = new javax.swing.GroupLayout(ThanhChucnang);
        ThanhChucnang.setLayout(ThanhChucnangLayout);
        ThanhChucnangLayout.setHorizontalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThanhChucnangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaphieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        ThanhChucnangLayout.setVerticalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhChucnangLayout.createSequentialGroup()
                .addGroup(ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Giaodien.setLayout(new java.awt.CardLayout());

        tbPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPhanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tbPhanquyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã phân quyền", "Tên quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhanquyen.setGridColor(new java.awt.Color(0, 0, 0));
        tbPhanquyen.setRowHeight(35);
        tbPhanquyen.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbPhanquyen.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbPhanquyen);

        javax.swing.GroupLayout XemPhanquyenLayout = new javax.swing.GroupLayout(XemPhanquyen);
        XemPhanquyen.setLayout(XemPhanquyenLayout);
        XemPhanquyenLayout.setHorizontalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        XemPhanquyenLayout.setVerticalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemPhanquyenLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Giaodien.add(XemPhanquyen, "Xem");

        PanPhanquyen.setBackground(new java.awt.Color(255, 255, 255));
        PanPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        PanPhanquyen.setPreferredSize(new java.awt.Dimension(930, 270));

        Nhapten.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Nhapten.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nhapten.setText("Nhập tên quyền:");

        txtNhapten.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNhapten.setText("jTextField1");
        txtNhapten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Quanlychucnang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Quanlychucnang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Quanlychucnang.setText("Quản lý chức năng");
        Quanlychucnang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txQuanlysach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach.setText("Quản lý phim");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txQuanlynhanvien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynhanvien.setText("Quản lý lịch chiếu");

        txQuanlyphieunhapsach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieunhapsach.setText("Quản lý phòng chiếu");

        txQuanlydocgia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlydocgia.setText("Quản lý ăn vặt");

        txQuanlyphanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphanquyen.setText("Quản lý ưu đãi");

        txQuanlyphieumuon.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieumuon.setText("Quản lý nhân viên");

        txQuanlytaikhoan.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlytaikhoan.setText("Quản lý khách hàng");

        txQuanlythongke.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlythongke.setText("Quản lý thống kê");

        txQuanlynguonnhap.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynguonnhap.setText("Quản lý hợp đồng");

        btnThemquyen.setBackground(new java.awt.Color(0, 122, 77));
        btnThemquyen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnThemquyen.setForeground(new java.awt.Color(255, 255, 255));
        btnThemquyen.setText("Thêm quyền");
        btnThemquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        txQuanlysach1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach1.setText("Quản lý nhà phân phối");

        txQuanlysach2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach2.setText("Quản lý tài khoản");

        txQuanlysach3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach3.setText("Quản lý phân quyền");

        javax.swing.GroupLayout PanPhanquyenLayout = new javax.swing.GroupLayout(PanPhanquyen);
        PanPhanquyen.setLayout(PanPhanquyenLayout);
        PanPhanquyenLayout.setHorizontalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Nhapten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txQuanlysach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quanlychucnang, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txQuanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphieunhapsach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlydocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlytaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlythongke, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlynguonnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quanlyanvat)
                            .addComponent(Quanlyphongchieu)
                            .addComponent(Quanlyuudai)
                            .addComponent(Quanlynhanvien)
                            .addComponent(Quanlyhopdong)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quanlykhachhang)
                                    .addComponent(Quanlythongke))
                                .addGap(618, 618, 618)
                                .addComponent(btnThemquyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addComponent(Quanlyphim)
                                .addGap(97, 97, 97)
                                .addComponent(txQuanlysach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100)
                                .addComponent(Quanlynpp))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanPhanquyenLayout.createSequentialGroup()
                                .addComponent(Quanlylichchieu)
                                .addGap(97, 97, 97)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addComponent(txQuanlysach3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Quanlyphanquyen))
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addComponent(txQuanlysach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Quanlytaikhoan)))))
                        .addGap(387, 387, 387))))
        );
        PanPhanquyenLayout.setVerticalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(Quanlyhopdong))
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txQuanlyphieumuon)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                .addComponent(Quanlychucnang)
                                                .addGap(18, 18, 18)
                                                .addComponent(txQuanlysach)
                                                .addGap(37, 37, 37))
                                            .addComponent(Quanlylichchieu, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                            .addComponent(txQuanlysach1)
                                                            .addGap(1, 1, 1))
                                                        .addComponent(Quanlynpp, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                            .addComponent(txQuanlysach2)
                                                            .addGap(1, 1, 1))
                                                        .addComponent(Quanlytaikhoan, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                    .addComponent(Quanlyphim)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txQuanlynhanvien))))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                .addComponent(txQuanlyphieunhapsach)
                                                .addGap(37, 37, 37))
                                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                    .addComponent(txQuanlysach3)
                                                    .addGap(1, 1, 1))
                                                .addComponent(Quanlyphanquyen, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                        .addComponent(Quanlyphongchieu)
                                        .addGap(18, 18, 18)
                                        .addComponent(txQuanlydocgia))
                                    .addComponent(Quanlyanvat, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txQuanlyphanquyen)
                                    .addComponent(Quanlyuudai))
                                .addGap(18, 18, 18)
                                .addComponent(Quanlynhanvien)))
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quanlythongke, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Quanlykhachhang)
                                            .addComponent(txQuanlytaikhoan))
                                        .addGap(18, 18, 18)
                                        .addComponent(txQuanlythongke)))
                                .addGap(18, 18, 18)
                                .addComponent(txQuanlynguonnhap))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnThemquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ThemPhanquyenLayout = new javax.swing.GroupLayout(ThemPhanquyen);
        ThemPhanquyen.setLayout(ThemPhanquyenLayout);
        ThemPhanquyenLayout.setHorizontalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ThemPhanquyenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanPhanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ThemPhanquyenLayout.setVerticalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ThemPhanquyenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanPhanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Giaodien.add(ThemPhanquyen, "Them");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThanhChucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Giaodien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ThanhChucnang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Giaodien, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
           CardLayout card = (CardLayout) Giaodien.getLayout();
        card.show(Giaodien, "Them");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
       // TODO add your handling code here:
       CardLayout card = (CardLayout) Giaodien.getLayout();
       card.show(Giaodien,"Xem");
    }//GEN-LAST:event_btnXemActionPerformed

    private void btnXoaphieuActionPerformed(java.awt.event.ActionEvent evt) {
    // Kiểm tra xem đã chọn dòng nào trong bảng chưa
    int selectedRow = tbPhanquyen.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
                "Vui lòng chọn phân quyền cần xóa!", 
                "Thông báo", 
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Lấy mã phân quyền từ dòng đã chọn (cột đầu tiên)
    String maPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 0).toString();
    String tenPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 1).toString();
    
    // Kiểm tra xem phân quyền có đang được sử dụng bởi tài khoản nào không
    if (phanQuyenDAO.kiemTraPhanQuyenDangSuDung(maPhanQuyen)) {
        JOptionPane.showMessageDialog(this, 
                "Không thể xóa phân quyền '" + tenPhanQuyen + "' vì đang được sử dụng bởi một hoặc nhiều tài khoản!",
                "Lỗi", 
                JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Hiển thị hộp thoại xác nhận
    int option = JOptionPane.showConfirmDialog(this, 
            "Bạn có chắc muốn xóa phân quyền '" + tenPhanQuyen + "'?", 
            "Xác nhận xóa", 
            JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        // Thực hiện xóa phân quyền
        boolean ketQua = phanQuyenDAO.xoaPhanQuyen(maPhanQuyen);
        
        if (ketQua) {
            JOptionPane.showMessageDialog(this, 
                    "Xóa phân quyền thành công!", 
                    "Thông báo", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Load lại bảng phân quyền
            loadTableData();
        } else {
            JOptionPane.showMessageDialog(this, 
                    "Xóa phân quyền thất bại!", 
                    "Lỗi", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}

// Phương thức xử lý khi nhấn nút Chi tiết
private void btnChitietActionPerformed(java.awt.event.ActionEvent evt) {
    // Kiểm tra xem đã chọn dòng nào trong bảng chưa
    int selectedRow = tbPhanquyen.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, 
                "Vui lòng chọn phân quyền để xem chi tiết!", 
                "Thông báo", 
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Lấy mã phân quyền và tên phân quyền từ dòng đã chọn
    String maPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 0).toString();
    String tenPhanQuyen = tbPhanquyen.getValueAt(selectedRow, 1).toString();
    
    // Lấy danh sách chức năng của phân quyền
    ArrayList<String> danhSachChucNang = phanQuyenDAO.getChiTietPhanQuyen(maPhanQuyen);
    
    if (danhSachChucNang.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
                "Phân quyền '" + tenPhanQuyen + "' không có chức năng nào!", 
                "Thông báo", 
                JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Tạo nội dung hiển thị chi tiết
    StringBuilder message = new StringBuilder();
    message.append("Chi tiết phân quyền: ").append(tenPhanQuyen).append(" (").append(maPhanQuyen).append(")\n\n");
    message.append("Các chức năng:\n");
    
    for (int i = 0; i < danhSachChucNang.size(); i++) {
        message.append(i + 1).append(". ").append(danhSachChucNang.get(i)).append("\n");
    }
    
    // Hiển thị hộp thoại thông báo chi tiết
    JOptionPane.showMessageDialog(this, 
            message.toString(), 
            "Chi tiết phân quyền", 
            JOptionPane.INFORMATION_MESSAGE);
}
    
     // Phương thức load dữ liệu phân quyền vào bảng
    private void loadTableData() {
        // Xóa dữ liệu cũ
        tableModel.setRowCount(0);
        
        // Lấy danh sách phân quyền từ DAO
        ArrayList<PhanQuyenDTO> danhSachPhanQuyen = phanQuyenDAO.getDanhSachPhanQuyen();
        
        // Thêm từng phân quyền vào bảng
        for (PhanQuyenDTO phanQuyen : danhSachPhanQuyen) {
            Object[] row = {
                phanQuyen.getMaPhanQuyen(),
                phanQuyen.getTenPhanQuyen()
            };
            
            tableModel.addRow(row);
        }
    }
    
    // Sự kiện khi nhấn nút "Thêm quyền"
    private void btnThemquyenActionPerformed(java.awt.event.ActionEvent evt) {
        // Lấy tên phân quyền từ textfield
        String tenPhanQuyen = txtNhapten.getText().trim();
        
        // Kiểm tra tên phân quyền
        if (tenPhanQuyen.isEmpty() || tenPhanQuyen.equals("Nhập tên phân quyền")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên phân quyền!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtNhapten.requestFocus();
            return;
        }
        
        // Kiểm tra tên phân quyền đã tồn tại chưa
        if (phanQuyenDAO.kiemTraTenPhanQuyen(tenPhanQuyen)) {
            JOptionPane.showMessageDialog(this, "Tên phân quyền đã tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtNhapten.requestFocus();
            return;
        }
        
        // Tạo danh sách chứa các checkbox được chọn
        ArrayList<String> danhSachMaChucNang = new ArrayList<>();
        
        // Kiểm tra từng checkbox và thêm mã chức năng tương ứng vào danh sách
        if (Quanlyphim.isSelected()) {
            danhSachMaChucNang.add("Q1");
        }
        if (Quanlylichchieu.isSelected()) {
            danhSachMaChucNang.add("Q2");
        }
        if (Quanlyphongchieu.isSelected()) {
            danhSachMaChucNang.add("Q3");
        }
        if (Quanlyanvat.isSelected()) {
            danhSachMaChucNang.add("Q4");
        }
        if (Quanlyuudai.isSelected()) {
            danhSachMaChucNang.add("Q5");
        }
        if (Quanlynhanvien.isSelected()) {
            danhSachMaChucNang.add("Q6");
        }
        if (Quanlykhachhang.isSelected()) {
            danhSachMaChucNang.add("Q7");
        }
        if (Quanlythongke.isSelected()) {
            danhSachMaChucNang.add("Q8");
        }
        if (Quanlyhopdong.isSelected()) {
            danhSachMaChucNang.add("Q9");
        }
        if (Quanlynpp.isSelected()) {
            danhSachMaChucNang.add("Q10");
        }
        if (Quanlytaikhoan.isSelected()) {
            danhSachMaChucNang.add("Q11");
        }
        if (Quanlyphanquyen.isSelected()) {
            danhSachMaChucNang.add("Q12");
        }
        
        // Kiểm tra xem có chọn ít nhất một chức năng không
        if (danhSachMaChucNang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ít nhất một chức năng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Tạo mã phân quyền mới
        String maPhanQuyen = phanQuyenDAO.taoMaPhanQuyenMoi();
        
        // Thêm phân quyền với các chức năng đã chọn
        boolean ketQua = phanQuyenDAO.themPhanQuyen(maPhanQuyen, tenPhanQuyen, danhSachMaChucNang);
        
        if (ketQua) {
            JOptionPane.showMessageDialog(this, "Thêm phân quyền thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            
            // Load lại bảng phân quyền
            loadTableData();
            
            // Reset form
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm phân quyền thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Phương thức reset form
    private void resetForm() {
        txtNhapten.setText("Nhập tên phân quyền");
        
        // Bỏ chọn tất cả checkbox
        Quanlyphim.setSelected(false);
        Quanlylichchieu.setSelected(false);
        Quanlyphongchieu.setSelected(false);
        Quanlyanvat.setSelected(false);
        Quanlyuudai.setSelected(false);
        Quanlynhanvien.setSelected(false);
        Quanlykhachhang.setSelected(false);
        Quanlythongke.setSelected(false);
        Quanlyhopdong.setSelected(false);
        Quanlynpp.setSelected(false);
        Quanlytaikhoan.setSelected(false);
        Quanlyphanquyen.setSelected(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Giaodien;
    private javax.swing.JLabel Nhapten;
    private javax.swing.JPanel PanPhanquyen;
    private javax.swing.JCheckBox Quanlyanvat;
    private javax.swing.JLabel Quanlychucnang;
    private javax.swing.JCheckBox Quanlyhopdong;
    private javax.swing.JCheckBox Quanlykhachhang;
    private javax.swing.JCheckBox Quanlylichchieu;
    private javax.swing.JCheckBox Quanlynhanvien;
    private javax.swing.JCheckBox Quanlynpp;
    private javax.swing.JCheckBox Quanlyphanquyen;
    private javax.swing.JCheckBox Quanlyphim;
    private javax.swing.JCheckBox Quanlyphongchieu;
    private javax.swing.JCheckBox Quanlytaikhoan;
    private javax.swing.JCheckBox Quanlythongke;
    private javax.swing.JCheckBox Quanlyuudai;
    private javax.swing.JPanel ThanhChucnang;
    private javax.swing.JPanel ThemPhanquyen;
    private javax.swing.JPanel XemPhanquyen;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemquyen;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoaphieu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbPhanquyen;
    private javax.swing.JLabel txQuanlydocgia;
    private javax.swing.JLabel txQuanlynguonnhap;
    private javax.swing.JLabel txQuanlynhanvien;
    private javax.swing.JLabel txQuanlyphanquyen;
    private javax.swing.JLabel txQuanlyphieumuon;
    private javax.swing.JLabel txQuanlyphieunhapsach;
    private javax.swing.JLabel txQuanlysach;
    private javax.swing.JLabel txQuanlysach1;
    private javax.swing.JLabel txQuanlysach2;
    private javax.swing.JLabel txQuanlysach3;
    private javax.swing.JLabel txQuanlytaikhoan;
    private javax.swing.JLabel txQuanlythongke;
    private javax.swing.JTextField txtNhapten;
    // End of variables declaration//GEN-END:variables
}
