/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author dinhp
 */
public class PhanquyenGUI extends javax.swing.JPanel {

    /**
     * Creates new form PhanquyenGUI
     */
    public PhanquyenGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ThanhChucnang = new javax.swing.JPanel();
        btnXem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoaphieu = new javax.swing.JButton();
        btnChitiet = new javax.swing.JButton();
        Giaodien = new javax.swing.JPanel();
        XemPhanquyen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhanquyen = new javax.swing.JTable();
        ThemPhanquyen = new javax.swing.JPanel();
        PanPhanquyen = new javax.swing.JPanel();
        Nhapten = new javax.swing.JLabel();
        txtNhapten = new javax.swing.JTextField();
        Quanlychucnang = new javax.swing.JLabel();
        txQuanlysach = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txQuanlynhanvien = new javax.swing.JLabel();
        txQuanlyphieunhapsach = new javax.swing.JLabel();
        txQuanlydocgia = new javax.swing.JLabel();
        txQuanlyphanquyen = new javax.swing.JLabel();
        txQuanlyphieumuon = new javax.swing.JLabel();
        txQuanlytaikhoan = new javax.swing.JLabel();
        txQuanlythongke = new javax.swing.JLabel();
        txQuanlynguonnhap = new javax.swing.JLabel();
        Quanlysach = new javax.swing.JCheckBox();
        Quanlynhanvien = new javax.swing.JCheckBox();
        Quanlyphieunhapsach = new javax.swing.JCheckBox();
        Quanlydocgia = new javax.swing.JCheckBox();
        Quanlyphanquyen = new javax.swing.JCheckBox();
        Quanlyphieumuon = new javax.swing.JCheckBox();
        Quanlytaikhoan = new javax.swing.JCheckBox();
        Quanlythongke = new javax.swing.JCheckBox();
        Quanlynguonnhap = new javax.swing.JCheckBox();
        btnCapnhat = new javax.swing.JButton();
        btnThemquyen = new javax.swing.JButton();
        txQuanlysach1 = new javax.swing.JLabel();
        Quanlysach1 = new javax.swing.JCheckBox();
        txQuanlysach2 = new javax.swing.JLabel();
        Quanlysach2 = new javax.swing.JCheckBox();
        txQuanlysach3 = new javax.swing.JLabel();
        Quanlysach3 = new javax.swing.JCheckBox();

        jPanel1.setPreferredSize(new java.awt.Dimension(1092, 533));

        ThanhChucnang.setBackground(new java.awt.Color(255, 255, 255));
        ThanhChucnang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));

        btnXem.setBackground(new java.awt.Color(153, 153, 153));
        btnXem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/view.png"))); // NOI18N
        btnXem.setText("Xem");
        btnXem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXem.setContentAreaFilled(false);
        btnXem.setFocusPainted(false);
        btnXem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXem.setMaximumSize(new java.awt.Dimension(50, 72));
        btnXem.setMinimumSize(new java.awt.Dimension(50, 72));
        btnXem.setPreferredSize(new java.awt.Dimension(50, 72));
        btnXem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnThem.setBackground(new java.awt.Color(153, 153, 153));
        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThem.setContentAreaFilled(false);
        btnThem.setFocusPainted(false);
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnXoaphieu.setBackground(new java.awt.Color(153, 153, 153));
        btnXoaphieu.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaphieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete_i.png"))); // NOI18N
        btnXoaphieu.setText("Xóa phân quyền");
        btnXoaphieu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoaphieu.setContentAreaFilled(false);
        btnXoaphieu.setFocusPainted(false);
        btnXoaphieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaphieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnChitiet.setBackground(new java.awt.Color(153, 153, 153));
        btnChitiet.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnChitiet.setText("Chi tiết");
        btnChitiet.setToolTipText("");
        btnChitiet.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChitiet.setContentAreaFilled(false);
        btnChitiet.setFocusPainted(false);
        btnChitiet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChitiet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout ThanhChucnangLayout = new javax.swing.GroupLayout(ThanhChucnang);
        ThanhChucnang.setLayout(ThanhChucnangLayout);
        ThanhChucnangLayout.setHorizontalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThanhChucnangLayout.createSequentialGroup()
                .addContainerGap(689, Short.MAX_VALUE)
                .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaphieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        ThanhChucnangLayout.setVerticalGroup(
            ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThanhChucnangLayout.createSequentialGroup()
                .addGroup(ThanhChucnangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Giaodien.setLayout(new java.awt.CardLayout());

        tbPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbPhanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tbPhanquyen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã phân quyền", "Tên quyền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPhanquyen.setGridColor(new java.awt.Color(0, 0, 0));
        tbPhanquyen.setRowHeight(35);
        tbPhanquyen.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tbPhanquyen.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tbPhanquyen);

        javax.swing.GroupLayout XemPhanquyenLayout = new javax.swing.GroupLayout(XemPhanquyen);
        XemPhanquyen.setLayout(XemPhanquyenLayout);
        XemPhanquyenLayout.setHorizontalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        XemPhanquyenLayout.setVerticalGroup(
            XemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(XemPhanquyenLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Giaodien.add(XemPhanquyen, "Xem");

        PanPhanquyen.setBackground(new java.awt.Color(255, 255, 255));
        PanPhanquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        PanPhanquyen.setPreferredSize(new java.awt.Dimension(930, 270));

        Nhapten.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Nhapten.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Nhapten.setText("Nhập tên quyền:");

        txtNhapten.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNhapten.setText("jTextField1");
        txtNhapten.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Quanlychucnang.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Quanlychucnang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Quanlychucnang.setText("Quản lý chức năng");
        Quanlychucnang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txQuanlysach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach.setText("Quản lý phim");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        txQuanlynhanvien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynhanvien.setText("Quản lý lịch chiếu");

        txQuanlyphieunhapsach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieunhapsach.setText("Quản lý phòng chiếu");

        txQuanlydocgia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlydocgia.setText("Quản lý ăn vặt");

        txQuanlyphanquyen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphanquyen.setText("Quản lý ưu đãi");

        txQuanlyphieumuon.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlyphieumuon.setText("Quản lý nhân viên");

        txQuanlytaikhoan.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlytaikhoan.setText("Quản lý khách hàng");

        txQuanlythongke.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlythongke.setText("Quản lý thống kê");

        txQuanlynguonnhap.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlynguonnhap.setText("Quản lý hợp đồng");

        btnCapnhat.setBackground(new java.awt.Color(255, 204, 0));
        btnCapnhat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        btnThemquyen.setBackground(new java.awt.Color(0, 122, 77));
        btnThemquyen.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnThemquyen.setForeground(new java.awt.Color(255, 255, 255));
        btnThemquyen.setText("Thêm quyền");
        btnThemquyen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 3));

        txQuanlysach1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach1.setText("Quản lý nhà phân phối");

        txQuanlysach2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach2.setText("Quản lý tài khoản");

        txQuanlysach3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txQuanlysach3.setText("Quản lý phân quyền");

        javax.swing.GroupLayout PanPhanquyenLayout = new javax.swing.GroupLayout(PanPhanquyen);
        PanPhanquyen.setLayout(PanPhanquyenLayout);
        PanPhanquyenLayout.setHorizontalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Nhapten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txQuanlysach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Quanlychucnang, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txQuanlynhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphieunhapsach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlydocgia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlyphieumuon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlytaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlythongke, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txQuanlynguonnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quanlydocgia)
                            .addComponent(Quanlyphieunhapsach)
                            .addComponent(Quanlyphanquyen)
                            .addComponent(Quanlyphieumuon)
                            .addComponent(Quanlytaikhoan)
                            .addComponent(Quanlythongke)
                            .addComponent(Quanlynguonnhap))
                        .addGap(620, 620, 620)
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemquyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addComponent(Quanlysach)
                                .addGap(97, 97, 97)
                                .addComponent(txQuanlysach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(100, 100, 100)
                                .addComponent(Quanlysach1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanPhanquyenLayout.createSequentialGroup()
                                .addComponent(Quanlynhanvien)
                                .addGap(97, 97, 97)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addComponent(txQuanlysach3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Quanlysach3))
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addComponent(txQuanlysach2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(100, 100, 100)
                                        .addComponent(Quanlysach2)))))
                        .addGap(387, 387, 387))))
        );
        PanPhanquyenLayout.setVerticalGroup(
            PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nhapten, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                        .addComponent(btnThemquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGap(334, 334, 334)
                                .addComponent(Quanlynguonnhap))
                            .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txQuanlyphieumuon)
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                        .addComponent(Quanlychucnang)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txQuanlysach)
                                                        .addGap(37, 37, 37))
                                                    .addComponent(Quanlynhanvien, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                                    .addComponent(txQuanlysach1)
                                                                    .addGap(1, 1, 1))
                                                                .addComponent(Quanlysach1, javax.swing.GroupLayout.Alignment.TRAILING))
                                                            .addGap(18, 18, 18)
                                                            .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                                    .addComponent(txQuanlysach2)
                                                                    .addGap(1, 1, 1))
                                                                .addComponent(Quanlysach2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                        .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                            .addComponent(Quanlysach)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txQuanlynhanvien))))
                                                .addGap(18, 18, 18)
                                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                                        .addComponent(txQuanlyphieunhapsach)
                                                        .addGap(37, 37, 37))
                                                    .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                            .addComponent(txQuanlysach3)
                                                            .addGap(1, 1, 1))
                                                        .addComponent(Quanlysach3, javax.swing.GroupLayout.Alignment.TRAILING))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanPhanquyenLayout.createSequentialGroup()
                                                .addComponent(Quanlyphieunhapsach)
                                                .addGap(18, 18, 18)
                                                .addComponent(txQuanlydocgia))
                                            .addComponent(Quanlydocgia, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txQuanlyphanquyen)
                                            .addComponent(Quanlyphanquyen))
                                        .addGap(18, 18, 18)
                                        .addComponent(Quanlyphieumuon)))
                                .addGap(18, 18, 18)
                                .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Quanlythongke, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanPhanquyenLayout.createSequentialGroup()
                                        .addGroup(PanPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Quanlytaikhoan)
                                            .addComponent(txQuanlytaikhoan))
                                        .addGap(18, 18, 18)
                                        .addComponent(txQuanlythongke)))
                                .addGap(18, 18, 18)
                                .addComponent(txQuanlynguonnhap)))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout ThemPhanquyenLayout = new javax.swing.GroupLayout(ThemPhanquyen);
        ThemPhanquyen.setLayout(ThemPhanquyenLayout);
        ThemPhanquyenLayout.setHorizontalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ThemPhanquyenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanPhanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        ThemPhanquyenLayout.setVerticalGroup(
            ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
            .addGroup(ThemPhanquyenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ThemPhanquyenLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanPhanquyen, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Giaodien.add(ThemPhanquyen, "Them");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThanhChucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Giaodien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ThanhChucnang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Giaodien, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Giaodien;
    private javax.swing.JLabel Nhapten;
    private javax.swing.JPanel PanPhanquyen;
    private javax.swing.JLabel Quanlychucnang;
    private javax.swing.JCheckBox Quanlydocgia;
    private javax.swing.JCheckBox Quanlynguonnhap;
    private javax.swing.JCheckBox Quanlynhanvien;
    private javax.swing.JCheckBox Quanlyphanquyen;
    private javax.swing.JCheckBox Quanlyphieumuon;
    private javax.swing.JCheckBox Quanlyphieunhapsach;
    private javax.swing.JCheckBox Quanlysach;
    private javax.swing.JCheckBox Quanlysach1;
    private javax.swing.JCheckBox Quanlysach2;
    private javax.swing.JCheckBox Quanlysach3;
    private javax.swing.JCheckBox Quanlytaikhoan;
    private javax.swing.JCheckBox Quanlythongke;
    private javax.swing.JPanel ThanhChucnang;
    private javax.swing.JPanel ThemPhanquyen;
    private javax.swing.JPanel XemPhanquyen;
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnChitiet;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemquyen;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoaphieu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tbPhanquyen;
    private javax.swing.JLabel txQuanlydocgia;
    private javax.swing.JLabel txQuanlynguonnhap;
    private javax.swing.JLabel txQuanlynhanvien;
    private javax.swing.JLabel txQuanlyphanquyen;
    private javax.swing.JLabel txQuanlyphieumuon;
    private javax.swing.JLabel txQuanlyphieunhapsach;
    private javax.swing.JLabel txQuanlysach;
    private javax.swing.JLabel txQuanlysach1;
    private javax.swing.JLabel txQuanlysach2;
    private javax.swing.JLabel txQuanlysach3;
    private javax.swing.JLabel txQuanlytaikhoan;
    private javax.swing.JLabel txQuanlythongke;
    private javax.swing.JTextField txtNhapten;
    // End of variables declaration//GEN-END:variables
}
